name: "main workflow"

on:
  pull_request:
    branches:
      - dev

env:
  PORT: 3000

jobs:
  build:
    name: laravel web app
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306

        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: false
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USERNAME: root
            MYSQL_DATABASE: test

    
    steps:
      - name: php install
        uses: shivammathur/setup-php@v2
        with: 
          php-version: '8.2' 

      - name: checkout branch
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          composer install

      - name: env install
        run: |
          cp .env.ci .env

      - name: Generate key 
        run: |
          php artisan key:generate

      - name: Migrate the database
        run: |
          php artisan key:generate

      - name: Unit testing
        run: |
          php artisan test
